services:
  # 1. Base de données PostgreSQL + TimescaleDB (Version 2.14 avec PG15)
  postgres:
    image: timescale/timescaledb:2.14.2-pg15
    container_name: flotte-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flotte_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Redis (Version 7.2)
  redis:
    image: redis:7.2-alpine
    container_name: flotte-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 3. Apache Kafka (Image officielle - Version 3.7.0 - Mode KRaft)
  kafka:
    image: apache/kafka:3.7.0
    container_name: flotte-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    
    restart: unless-stopped

  # 4. Keycloak (Latest)
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: flotte-keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/flotte_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: password
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: "xforwarded"
    ports:
      - "8180:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - postgres
    restart: unless-stopped

     # 5. Interface d'administration web pour PostgreSQL (Façon phpMyAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: flotte-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@flotte.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  # 6. Microservice Véhicules (Spring Boot)
  vehicle:
    build:
      context: ./services/vehicle-service
      dockerfile: Dockerfile
    container_name: flotte-vehicle
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/flotte_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      # Configuration pour l'Agent Java OpenTelemetry
      - OTEL_SERVICE_NAME=vehicle-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED=true
      - OTEL_INSTRUMENTATION_LOGBACK_APPENDER_EXPERIMENTAL_LOG_ATTRIBUTES=true
      - KEYCLOAK_ISSUER_URI=http://keycloak:8080/realms/gestion-flotte
      - KEYCLOAK_JWK_SET_URI=http://keycloak:8080/realms/gestion-flotte/protocol/openid-connect/certs
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - otel-collector
      - keycloak
    restart: unless-stopped

volumes:
  postgres_data:
  kafka_data:

 