server:
  port: 8080

spring:
  application:
    name: vehicle-service
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      resourceserver:
        jwt:
          # On ne met PAS issuer-uri ici pour éviter que Spring essaie de faire de la découverte OIDC sur le réseau
          # On utilisera une vérification manuelle dans SecurityConfig si nécessaire
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:http://localhost:8180/realms/gestion-flotte/protocol/openid-connect/certs}

  # Configuration de la base de donnees (PostgreSQL)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/vehicle_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # Configuration Hibernate / JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: jackson

  # Configuration Kafka
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: vehicle-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.flotte.vehicle.events.KafkaEventEnvelope:com.flotte.vehicle.events.KafkaEventEnvelope"

# Configuration de l'observabilite
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
    metrics:
      export:
        url: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
    logging:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
logging:
  otlp:
    enabled: true
  level:
    root: INFO
    io.opentelemetry: INFO
    io.micrometer: INFO
