server:
  port: 8080

spring:
  application:
    name: vehicle-service

  # Configuration de la base de donnees (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/flotte_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  # Configuration Hibernate / JPA
  jpa:
    hibernate:
      ddl-auto: none # Modifié pour laisser ton script SQL gérer la base
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        type:
          json_format_mapper: jackson

  # Configuration Kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: vehicle-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"