apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flotte-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
spec:
  ingressClassName: nginx
  rules:
    - host: flotte.local
      http:
        paths:
          - path: /(grafana)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana
                port:
                  number: 3000

          - path: /(graphql)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: graphql-gateway-service
                port:
                  number: 4000

          - path: /api/(vehicles)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: vehicle-service
                port:
                  number: 8080
          - path: /api/(drivers)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.driver.name }}
                port:
                  number: {{ .Values.services.driver.port }}
          - path: /api/(maintenance)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.services.maintenance.name }}
                port:
                  number: {{ .Values.services.maintenance.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jaeger-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: flotte.local
      http:
        paths:
          - path: /jaeger
            pathType: ImplementationSpecific
            backend:
              service:
                name: jaeger
                port:
                  number: 16686

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
spec:
  ingressClassName: nginx
  rules:
    - host: flotte.local
      http:
        paths:
          - path: /auth
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
