namespace: flotte-namespace

# Configuration des Services Applicatifs
services:
  vehicle:
    name: vehicle-service
    image: vehicle-service:latest
    port: 8080
    replicas: 2
  driver:
    name: driver-service
    image: driver-service:latest
    port: 8080
    replicas: 1
    dbUrlKey: DRIVER_DATASOURCE_URL
  maintenance:
    name: maintenance-service
    image: maintenance-service:latest
    port: 8080
    replicas: 1
    dbUrlKey: MAINTENANCE_DATASOURCE_URL

# Configuration Keycloak (SSO)
keycloak_issuer: "http://keycloak-service:8080/auth/realms/gestion-flotte"
keycloak_jwk_set_uri: "http://keycloak-service:8080/auth/realms/gestion-flotte/protocol/openid-connect/certs"
