apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: flotte-namespace
spec:
  type: ExternalName
  externalName: graphql-gateway-service.flotte-namespace.svc.cluster.local
  ports:
  - port: 4000
