apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: flotte-namespace
spec:
  selector:
    app: location-service
  # selector matches deployment label app: location-service
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP