apiVersion: v2
name: fleet-infra
description: Infrastructure (PostgreSQL, Kafka, Redis, Observabilité) pour le projet
type: application
version: 1.0.0

# Dépendances téléchargées de Bitnami
dependencies:
  - name: postgresql
    version: "18.5.6"
    repository: "file://charts"

  - name: postgresql
    alias: postgresql-maintenance
    version: "18.5.6"
    repository: "file://charts"
    condition: postgresql-maintenance.enabled

  - name: postgresql
    alias: postgresql-driver
    version: "18.5.6"
    repository: "file://charts"
    condition: postgresql-driver.enabled

  - name: redis
    version: "25.3.2"
    repository: "file://charts"
