postgresql:
  auth:
    postgresPassword: "password"
    password: "password"
  primary:
    persistence:
      enabled: false # On désactive la persistance pour le dev local minikube pour éviter les soucis de droits

redis:
  auth:
    enabled: false # Pas de mot de passe pour redis en dev
