postgresql:
  auth:
    postgresPassword: "password"
    password: "password"
  primary:
    persistence:
      enabled: false

postgresql-maintenance:
  auth:
    postgresPassword: "password"
    password: "password"
  primary:
    persistence:
      enabled: false

postgresql-driver:
  auth:
    postgresPassword: "password"
    password: "password"
  primary:
    persistence:
      enabled: false

redis:
  auth:
    enabled: false
