namespace: flotte-namespace

# 1. Configuration de PostgreSQL principal (Vehicules)
postgresql:
  fullnameOverride: "postgres-service"
  auth:
    username: "admin"
    database: "flotte_db"
  primary:
    persistence:
      enabled: false
    initdb:
      scriptsConfigMap: "flotte-db-init"

# 1b. Configuration de PostgreSQL pour la Maintenance
postgresql-maintenance:
  enabled: true
  fullnameOverride: "postgres-maintenance-service"
  auth:
    username: "admin"
    database: "maintenance_db"
  primary:
    persistence:
      enabled: false
    initdb:
      scriptsConfigMap: "maintenance-db-init"

# 1c. Configuration de PostgreSQL pour le Service Conducteurs
postgresql-driver:
  enabled: true
  fullnameOverride: "postgres-driver-service"
  auth:
    username: "admin"
    database: "driver_db"
  primary:
    persistence:
      enabled: false
    initdb:
      scriptsConfigMap: "driver-db-init"

# 2. Configuration de Redis
redis:
  fullnameOverride: "redis-service"

  architecture: "standalone"

  auth:
    enabled: false
  
  master:
    persistence:
      enabled: false

# 3. Configuration de Kafka (KRaft mode)
kafka:
  image: confluentinc/cp-kafka:7.5.0
  port: 9092
