# 1. Configuration de PostgreSQL
postgresql:
  fullnameOverride: "postgres-service"

  auth:
    postgresUser: "admin"
    # postgresPassword retiré → dans values.secret.yaml.secret.yaml
    database: "flotte_db"

  primary:
    persistence:
      enabled: false

# 2. Configuration de Redis
redis:
  fullnameOverride: "redis-service"

  architecture: "standalone"

  auth:
    enabled: false
  
  master:
    persistence:
      enabled: false